 'use strict';
const fs=require('fs'),path=require('path'),os=require('os'),crypto=require('crypto'),{spawnSync}=require('child_process');
function arg(n,d=null){const i=process.argv.indexOf(n);return i>=0?process.argv[i+1]:d}function read(p){return JSON.parse(fs.readFileSync(p,'utf8'))}function write(p,x){fs.writeFileSync(p,JSON.stringify(x,null,2)+'\n')}function sha(p){return crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex')}function stamp(){return new Date().toISOString().replace(/[-:]/g,'').replace(/\..+/,'').replace('T','_')}
function main(){
 const root=path.resolve(arg('--root','C:/xampp/htdocs/color-search-test/tools/b1'));const a1=path.resolve(arg('--a1-run'));const py=arg('--python');const configPath=path.resolve(arg('--config',path.join(__dirname,'..','config','stylecolor_v0_8a2.config.json')));const mode=arg('--mode','real');const cfg=read(configPath);
 const obs=read(path.join(a1,'atomic_region_observations.json'));const a1m=read(path.join(a1,'run_manifest.json'));
 const outBase=path.resolve(arg('--out-base',path.join(root,'stylecolor-v0.8a2','runs')));fs.mkdirSync(outBase,{recursive:true});const run=path.join(outBase,`${stamp()}_${cfg.style_id}_v0_8a2`);fs.mkdirSync(run,{recursive:true});
 const items=[];for(const img of obs.images){let src=img.source_path;let status='A1_ORIGINAL_SOURCE';if(!src||!fs.existsSync(src)){src=path.join(a1,img.source_image_asset);status='NON_BYTE_IDENTICAL_FALLBACK_A1_JPEG'}items.push({image_id:img.image_id,source_path:src,source_sha256:status==='A1_ORIGINAL_SOURCE'?img.source_sha256:null,input_source_status:status})}
 write(path.join(run,'source_manifest.json'),{schema_version:'0.8a2.0',a1_run:a1,a1_run_manifest_sha256:sha(path.join(a1,'run_manifest.json')),items});
 const wp=path.resolve(__dirname,'..','python','a2_foundation_worker.py');const cp=spawnSync(py,[wp,'--manifest',path.join(run,'source_manifest.json'),'--config',configPath,'--out-dir',run,'--mode',mode],{encoding:'utf8',stdio:'inherit',timeout:7200000,env:{...process.env,PYTHONUNBUFFERED:'1'}});if(cp.status!==0)process.exit(cp.status||2);
 const mp=path.resolve(__dirname,'..','python','map_atomic_foundation.py');let x=spawnSync(py,[mp,'--a1-run',a1,'--a2-run',run],{encoding:'utf8',stdio:'inherit',timeout:600000});if(x.status!==0)process.exit(x.status||3);
 x=spawnSync(process.execPath,[path.resolve(__dirname,'assemble_a2.js'),a1,run],{encoding:'utf8',stdio:'inherit'});if(x.status!==0)process.exit(x.status||4);
 const fw=read(path.join(run,'foundation_worker_summary.json')),diag=read(path.join(run,'a2_diagnostics.json'));
 const manifest={schema_version:'0.8a2.0',name:'YOYO v0.8-A.2 Foundation Mask + Semantic Prior + Visual Embedding',version:'0.8a2.0',created_at:new Date().toISOString(),mode,upstream_a1_run:a1,upstream_status:'A1_ENGINEERING_VALIDATED_READY_FOR_A2_EVALUATION + A1_REGION_MODEL_INSUFFICIENT',foundation_model:cfg.foundation_mask.model,foundation_mask_role:'PRIOR_NOT_TRUTH',visual_embedding_model:`${cfg.visual_embedding.model}/${cfg.visual_embedding.pretrained}`,semantic_prior_semantics:'CLIP_COSINE_NOT_PROBABILITY',a1_relationship_action_authority:'NONE',atomic_regions_immutable:true,destructive_merges_executed:0,style_graph_built:false,production_authority:'NONE',node_version:process.version,python_executable:py,platform:{os:os.platform(),release:os.release(),arch:os.arch()},input_fallback_count:items.filter(x=>x.input_source_status!=='A1_ORIGINAL_SOURCE').length,summary:diag};write(path.join(run,'run_manifest.json'),manifest);
 x=spawnSync(process.execPath,[path.resolve(__dirname,'build_a2_audit.js'),run],{encoding:'utf8',stdio:'inherit'});if(x.status!==0)process.exit(x.status||5);fs.writeFileSync(path.join(outBase,'LATEST_RUN.txt'),run+'\n');console.log('RUN_DIR='+run)
}
main();
