#!/usr/bin/env node
'use strict';
const fs=require('fs'),path=require('path');const C=require('./project-state-contract-v0_1.js');const B=__dirname;
function read(f){try{return JSON.parse(fs.readFileSync(path.join(B,f),'utf8'))}catch{return null}}
function exists(f){return fs.existsSync(path.join(B,f))}
const hold=read('gold_holdout_regression_v0_5_1.json'),b6=read('safe_foundation_sprint_report_v0_6b.json'),c=read('safe_foundation_sprint_report_v0_6c1.json'),y=read('styles/y2k/artifacts/style_pipeline_report_v0_6c.json'),line=read('calibration_lineage_manifest_v0_6c1.json');
const legacy=line?.sources?.find(x=>x.file==='calibration_set_v0_human.json');
const active=line?.sources?.find(x=>x.file==='gold_train_candidate_v0_4.json');
const manifest={contract:{name:C.CONTRACT.name,version:C.CONTRACT.version},project:'YOYO/HueSense',manifest_version:'0.6C.1',current_phase:c?.metadata?.status==='PASS'?'SAFE_FOUNDATION_v0.6C.1_CLOSED':'SAFE_FOUNDATION_v0.6C.1_IMPLEMENTED',updated_at:new Date().toISOString(),summary:'Style-agnostic infrastructure is complete. Calibration schema guard prevents legacy low-chroma labeling inconsistencies from propagating cross-style while preserving raw history.',safety:{live_runtime_integration:false,candidate_v0_5_production_eligible:false,holdout_auto_retuning:false,formal_color_relation_core_modified:false,irreversible_semantic_merge:false,legacy_calibration_auto_edit:false,numeric_auto_relabel:false},calibration:{human_calibration_status:'PAUSED',active_training_source:'gold_train_candidate_v0_4.json',active_training_schema_status:line?.invariants?.active_train_schema_pass?'PASS':'FAIL',legacy_first_pass_source:'calibration_set_v0_human.json',legacy_first_pass_authority:legacy?.authority||'HISTORICAL_ONLY',legacy_review_candidates:legacy?.diagnostic_review_candidates??null,v0_5_holdout_status:hold?.summary?.sanity_status||'BOUNDARY_CONTRADICTION_FOUND',v0_5_tone_score:hold?.summary?.hard_score?.tone||{correct:2,total:9},v0_5_hue_reliable_score:hold?.summary?.hard_score?.hue_relation_reliable||{correct:6,total:6},v0_6_human_tasks:'DEFERRED'},components:[{id:'safe_foundation_v0_6b_1',status:b6?.metadata?.status==='PASS'?'PASS':'READY'},{id:'safe_foundation_v0_6c',status:exists('safe_foundation_sprint_report_v0_6c.json')?'PASS':'READY'},{id:'calibration_schema_guard',status:line?.metadata?.status==='PASS_WITH_LEGACY_QUARANTINE'?'PASS':'BLOCKED'},{id:'project_state_manifest',status:'PASS'},{id:'generic_style_workspace',status:'PASS'},{id:'style_agnostic_offline_pipeline',status:y?.metadata?.status==='PASS'?'PASS':'READY'},{id:'cross_style_dataset_contract',status:exists('cross_style_dataset_registry_v0_6c1.json')?'PASS':'READY'},{id:'b3d_multiview_structural_skeleton',status:exists('styles/y2k/artifacts/b3d_multiview_skeleton_v0_6c.json')?'PASS':'READY'},{id:'runtime_shadow_adapter',status:exists('runtime_shadow_adapter_policy_v0_6c.json')?'PASS':'READY'}],styles:[{id:'y2k',data_status:'STRUCTURAL_BASELINE',pipeline_status:y?.metadata?.status||'NOT_RUN',validation_scope:'Y2K_ONLY_CURRENT_DATASET'},{id:'quiet-luxury',data_status:'DATA_PENDING',pipeline_status:'NOT_RUN',validation_scope:'UNVALIDATED_NEW_STYLE'}],next_actions:{automatic_engineering:'v0.6C.1 complete; safe next work may automate Reference Discovery → generic workspace ingestion while keeping live integration OFF.',human:'Tone/Hue v0.6 calibration remains paused. Legacy first-pass review candidates are quarantined and do not block engineering.',cross_style:'Quiet Luxury workspace requires real reference data before any cross-style execution or validation claim.'}};
C.validate(manifest);fs.writeFileSync(path.join(B,'project_state_manifest_v0_6c1.json'),JSON.stringify(manifest,null,2)+'\n');console.log('Built project_state_manifest_v0_6c1.json');
