#!/usr/bin/env node
'use strict';
const fs=require('fs'),path=require('path'),crypto=require('crypto');const C=require('./cache-manifest-contract-v0_1.js'),R=require('./reference-manifest-contract-v0_1.js');
function arg(n,f){const i=process.argv.indexOf(n);return i>=0&&process.argv[i+1]?process.argv[i+1]:f}
function safe(v){return String(v||'item').replace(/[^a-zA-Z0-9._-]+/g,'_').slice(0,140)}function h12(v){return crypto.createHash('sha1').update(String(v)).digest('hex').slice(0,12)}function sha(p){return crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex')}
function imageSignatureOK(p){try{const b=fs.readFileSync(p);if(b.length<12)return false;const ascii=b.subarray(0,64).toString('ascii').toLowerCase();if(ascii.includes('<html')||ascii.includes('<!doctype'))return false;if(b[0]===0xff&&b[1]===0xd8&&b[2]===0xff)return true;if(b.subarray(0,8).equals(Buffer.from([0x89,0x50,0x4e,0x47,0x0d,0x0a,0x1a,0x0a])))return true;if(b.subarray(0,6).toString('ascii')==='GIF87a'||b.subarray(0,6).toString('ascii')==='GIF89a')return true;if(b.subarray(0,4).toString('ascii')==='RIFF'&&b.subarray(8,12).toString('ascii')==='WEBP')return true;if(b.subarray(0,2).toString('ascii')==='BM')return true;if((b[0]===0x49&&b[1]===0x49&&b[2]===0x2a&&b[3]===0x00)||(b[0]===0x4d&&b[1]===0x4d&&b[2]===0x00&&b[3]===0x2a))return true;const box=b.subarray(4,12).toString('ascii');if(box.startsWith('ftyp')&&(box.includes('avif')||box.includes('heic')||box.includes('mif1')))return true;return false}catch{return false}}
(async()=>{const refP=path.resolve(arg('--reference-manifest','reference_manifest_v0_6d.json')),cacheDir=path.resolve(arg('--cache-dir','b1_cache')),out=path.resolve(arg('--output','cache_manifest_v0_6d.json'));const r=JSON.parse(fs.readFileSync(refP,'utf8'));R.validate(r);const items=[];
for(const x of r.references){const variants=(x.url_variants||[{kind:'primary',cache_label:'primary',url:x.image_url,priority:1,skip:false}]).slice().sort((a,b)=>a.priority-b.priority);let chosen=null,primaryStatus='MISSING';const attempts=[];for(const v of variants){const fn=`${safe(x.reference_id)}_${safe(v.cache_label)}_${h12(v.url)}.img`,p=path.join(cacheDir,fn);if(v.kind==='primary'&&v.skip){primaryStatus='SKIPPED_BY_POLICY';attempts.push({kind:v.kind,status:'SKIPPED',cache_file:null});continue}if(!fs.existsSync(p)||fs.statSync(p).size<=0){if(v.kind==='primary')primaryStatus='MISSING';attempts.push({kind:v.kind,status:'MISSING',cache_file:null});continue}const ok=imageSignatureOK(p);if(v.kind==='primary')primaryStatus=ok?'DECODABLE':'INVALID';attempts.push({kind:v.kind,status:ok?'DECODABLE':'INVALID',cache_file:path.relative(path.dirname(out),p).replace(/\\/g,'/')});if(ok&&!chosen)chosen={v,p}}
items.push({reference_id:x.reference_id,cache_status:chosen?'CACHED':'MISSING',cache_file:chosen?path.relative(path.dirname(out),chosen.p).replace(/\\/g,'/'):null,bytes:chosen?fs.statSync(chosen.p).size:0,sha256:chosen?sha(chosen.p):null,selected_variant:chosen?.v?.kind||null,analysis_source:chosen?.v?.analysis_source||(chosen?.v?.kind==='primary'?'primary_image_url':null),fallback_used:chosen?.v?.kind==='fallback',primary_status:primaryStatus,attempts,requested_url_hash:crypto.createHash('sha256').update(String(x.image_url)).digest('hex')})}
const cached=items.filter(x=>x.cache_status==='CACHED').length,primaryFailures=items.filter(x=>x.primary_status!=='DECODABLE').length,m={contract:C.CONTRACT,style_id:r.style.id,metadata:{version:'0.6D',created_at:new Date().toISOString(),raw_image_urls_stored:false,cache_resolution:'pre-B1 filesystem scan + image-signature validation',sharp_decode_validation:false},items,summary:{total:items.length,cached,missing:items.length-cached,cache_ratio:items.length?cached/items.length:0,fallback_used:items.filter(x=>x.fallback_used).length,primary_failure_count:primaryFailures,primary_failure_ratio:items.length?primaryFailures/items.length:0}};C.validate(m);fs.mkdirSync(path.dirname(out),{recursive:true});fs.writeFileSync(out,JSON.stringify(m,null,2)+'\n');console.log(`Cache Manifest: ${cached}/${items.length} cached; primary failures ${primaryFailures}/${items.length} → ${out}`)})().catch(e=>{console.error('❌ '+e.stack);process.exit(1)});
