#!/usr/bin/env node
'use strict';
const fs=require('fs'),path=require('path');const U=require('./v0_7_common.js');const C=require('./perceptual-relation-contract-v0_7.js');const R=require('./perceptual-relation-candidate-v0_7.js');
const trainFile='v0_7_train_human.json';
if(fs.existsSync(path.join(__dirname,'v0_7_candidate_freeze.json')))throw new Error('Candidate already frozen. Validation-safe workflow forbids refitting in place. Start a new version instead.');
if(fs.existsSync(path.join(__dirname,'v0_7_validation_human.json')))throw new Error('Validation labels already exist; refitting is forbidden.');
if(!fs.existsSync(path.join(__dirname,trainFile))){console.log('HUMAN_TRAIN_REQUIRED: place v0_7_train_human.json in tools\\b1');process.exit(10)}
const d=U.read(trainFile);C.assertDirectHumanDataset(d,'TRAIN_CALIBRATION');if(d.cases.length!==24)throw new Error('Expected 24 train cases');
const graph=U.read('y2k_color_relation_graph.json'),em=U.edgeMap(graph);const rows=d.cases.map(c=>({c,e:em.get(c.pair_key||U.getPairFromCase(c))}));if(rows.some(x=>!x.e))throw new Error('Train edge missing');
function eligible(y,k){return y.confidence!=='low'&&y[k]!=='review'}
function macroRecall(truth,pred){const cls=[...new Set(truth)];if(!cls.length)return 0;return cls.reduce((s,c)=>{let n=0,ok=0;for(let i=0;i<truth.length;i++)if(truth[i]===c){n++;if(pred[i]===c)ok++}return s+(n?ok/n:0)},0)/cls.length}
function fit3On(subset,feature,labelKey){
  const ds=subset.filter(x=>eligible(x.c.human_label,labelKey)).map(x=>({x:x.e.physical_relations[feature],y:x.c.human_label[labelKey]}));
  if(ds.length<3)throw new Error('too few train labels for '+labelKey);
  const vals=[...new Set(ds.map(x=>x.x))].sort((a,b)=>a-b),cuts=[0,...vals.map((v,i)=>i<vals.length-1?(v+vals[i+1])/2:v+1e-8)];let best=null;
  for(const a of cuts)for(const b of cuts){if(a>=b)continue;const pred=ds.map(z=>z.x<=a?'similar':z.x>=b?'different':'similar_or_partial'),truth=ds.map(z=>z.y),macro=macroRecall(truth,pred),exact=pred.filter((p,i)=>p===truth[i]).length/ds.length;if(!best||macro>best.macro||(macro===best.macro&&exact>best.exact)||(macro===best.macro&&exact===best.exact&&(b-a)>(best.b-best.a)))best={a,b,macro,exact,n:ds.length};}
  if(!best)throw new Error('cannot fit '+labelKey);return best;
}
function fitBinaryOn(subset,feature,key,lowLabel,highLabel){
  const ds=subset.filter(x=>eligible(x.c.human_label,key)&&[lowLabel,highLabel].includes(x.c.human_label[key])).map(x=>({x:x.e.physical_relations[feature],y:x.c.human_label[key]}));
  if(ds.length<2)return null;const vals=[...new Set(ds.map(x=>x.x))].sort((a,b)=>a-b),cuts=[vals[0]-1e-8,...vals.map((v,i)=>i<vals.length-1?(v+vals[i+1])/2:v+1e-8)];let best=null;
  for(const t of cuts){const pred=ds.map(z=>z.x<t?lowLabel:highLabel),truth=ds.map(z=>z.y),macro=macroRecall(truth,pred),exact=pred.filter((p,i)=>p===truth[i]).length/ds.length;if(!best||macro>best.macro||(macro===best.macro&&exact>best.exact))best={t,macro,exact,n:ds.length}}
  return best;
}
function looAxis(feature,labelKey,type){let ok=0,n=0,truth=[],pred=[];for(let i=0;i<rows.length;i++){const y=rows[i].c.human_label;if(!eligible(y,labelKey))continue;const sub=rows.filter((_,j)=>j!==i);let p;if(type==='3'){const f=fit3On(sub,feature,labelKey);const x=rows[i].e.physical_relations[feature];p=x<=f.a?'similar':x>=f.b?'different':'similar_or_partial'}else{const f=fitBinaryOn(sub,feature,labelKey,type[0],type[1]);if(!f)continue;const x=rows[i].e.physical_relations[feature];p=x<f.t?type[0]:type[1]}n++;truth.push(y[labelKey]);pred.push(p);if(p===y[labelKey])ok++}return {correct:ok,total:n,exactRate:n?ok/n:null,macroRecall:n?macroRecall(truth,pred):null}}
const cv={lightness:looAxis('delta_L','lightness_relation','3'),chroma:looAxis('delta_C','chroma_relation','3'),hue_applicability:looAxis('min_chroma','hue_applicability',['low_chroma','reliable'])};
const light=fit3On(rows,'delta_L','lightness_relation'),chroma=fit3On(rows,'delta_C','chroma_relation'),ha=fitBinaryOn(rows,'min_chroma','hue_applicability','low_chroma','reliable');if(!ha)throw new Error('insufficient hue applicability labels');
const reliableRows=rows.filter(x=>x.c.human_label.hue_applicability==='reliable');const hr=fitBinaryOn(reliableRows,'circular_delta_H_degrees','hue_relation','same_or_adjacent','different');if(!hr)throw new Error('insufficient reliable hue labels');cv.hue_relation_reliable=looAxis('circular_delta_H_degrees','hue_relation',['same_or_adjacent','different']);
const rules=['CONSENSUS_AXES','CONSERVATIVE_DIFFERENT','LIGHTNESS_DOMINANT','CHROMA_DOMINANT'];const tonePred=Object.fromEntries(rules.map(r=>[r,[]]));const toneTruth=[];
for(let i=0;i<rows.length;i++){const y=rows[i].c.human_label;if(!eligible(y,'tone_relation'))continue;const sub=rows.filter((_,j)=>j!==i);const lf=fit3On(sub,'delta_L','lightness_relation'),cf=fit3On(sub,'delta_C','chroma_relation');const xL=rows[i].e.physical_relations.delta_L,xC=rows[i].e.physical_relations.delta_C;const l=xL<=lf.a?'similar':xL>=lf.b?'different':'similar_or_partial',c=xC<=cf.a?'similar':xC>=cf.b?'different':'similar_or_partial';toneTruth.push(y.tone_relation);for(const rule of rules)tonePred[rule].push(R.toneRule(l,c,rule))}
let br=null;for(const rule of rules){const pr=tonePred[rule],exact=pr.filter((p,i)=>p===toneTruth[i]).length/toneTruth.length,macro=macroRecall(toneTruth,pr);const x={rule,looExactRate:exact,looMacroRecall:macro,n:toneTruth.length};if(!br||macro>br.looMacroRecall||(macro===br.looMacroRecall&&exact>br.looExactRate))br=x}cv.tone_rule=br;
const config={metadata:{name:'YOYO Perceptual Relation Candidate v0.7',version:'0.7.0',status:'FROZEN_UNVALIDATED',fit_source:'v0_7_train_human.json',fit_authority:'DIRECT_HUMAN_BLIND',retired_holdout_used_for_fit:false,validation_labels_used_for_fit:false,production_gate_eligible:false,universality_status:'UNVALIDATED',candidate_frozen_at:new Date().toISOString()},lightness:{similarMax:light.a,differentMin:light.b},chroma:{similarMax:chroma.a,differentMin:chroma.b},hue:{minChromaReliable:ha.t,sameOrAdjacentMaxDeltaH:hr.t},tone:{rule:br.rule},train_cross_validation:cv,train_fit_summary:{lightness:{macroRecall:light.macro,exactRate:light.exact,n:light.n},chroma:{macroRecall:chroma.macro,exactRate:chroma.exact,n:chroma.n},hue_applicability:{macroRecall:ha.macro,exactRate:ha.exact,n:ha.n},hue_relation_reliable:{macroRecall:hr.macro,exactRate:hr.exact,n:hr.n}},warning:'All figures here are TRAIN/CROSS-VALIDATION diagnostics only. They are not independent validation accuracy.',pilot_gate:C.CONTRACT.preregistered_pilot_gate};U.write('perceptual_relation_candidate_config_v0_7.json',config);
const freeze={metadata:{name:'YOYO v0.7 Candidate Freeze',version:'0.7.0',status:'FROZEN_BEFORE_VALIDATION_LABELS'},candidate_config_sha256:U.fileSha('perceptual_relation_candidate_config_v0_7.json'),candidate_code_sha256:U.fileSha('perceptual-relation-candidate-v0_7.js'),train_labels_sha256:U.fileSha(trainFile),frozen_at:config.metadata.candidate_frozen_at,forbidden_after_freeze:['RETUNE_FROM_VALIDATION','READ_RETIRED_HOLDOUT_FOR_FORMULA_SELECTION','MODE_SPECIFIC_OVERRIDES']};U.write('v0_7_candidate_freeze.json',freeze);console.log('v0.7 Candidate FROZEN_UNVALIDATED. Validation labels have not been used.');console.log(`Tone rule selected by train LOO: ${br.rule}; LOO macro=${br.looMacroRecall.toFixed(3)}, exact=${br.looExactRate.toFixed(3)} (not validation)`);
