#!/usr/bin/env node
'use strict';
const fs=require('fs'),path=require('path'),crypto=require('crypto'),{spawnSync}=require('child_process');const B=__dirname;const stages=[];
function hash(f){const p=path.join(B,f);return fs.existsSync(p)?crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex'):null}
function read(f){try{return JSON.parse(fs.readFileSync(path.join(B,f),'utf8'))}catch{return null}}
function run(s,args=[]){console.log(`>>> ${s}`);const st=Date.now(),r=spawnSync(process.execPath,[path.join(B,s),...args],{stdio:'inherit',cwd:B});stages.push({script:s,args,status:r.status,elapsed_ms:Date.now()-st});if(r.status!==0){console.error(`\n❌ Sprint v0.6C.1 failed at ${s}`);process.exit(r.status||1)}}
const prior=read('safe_foundation_sprint_report_v0_6b.json');if(prior?.metadata?.status!=='PASS'){console.error('❌ v0.6B.1 PASS report not found. Run v0.6B.1 first.');process.exit(2)}
const protectedFiles=['tone-core.js','color-relation-core.js','color-relation-candidate-v0_5.js','y2k_color_relation_graph_v0_5_candidate.json','calibration_set_v0_human.json','gold_train_candidate_v0_4.json','gold_holdout_human_v0_5_2.json'];const before=Object.fromEntries(protectedFiles.map(f=>[f,hash(f)]));
console.log('=== YOYO Safe Foundation Sprint v0.6C.1 — Calibration-Safe Cross-Style One Chain ===');console.log('Human calibration: PAUSED');console.log('Legacy raw calibration: IMMUTABLE');console.log('Numeric auto-relabel: OFF');console.log('Live integration: OFF');console.log('Candidate promotion: FORBIDDEN');console.log('');
// Build/revalidate v0.6C structural infrastructure first.
run('project-state-contract.contract.test.js');run('style-workspace-contract.contract.test.js');
// NEW guard must pass before cross-style registry can be built.
run('perceptual-label-contract.contract.test.js');run('audit_calibration_lineage_v0_6c1.js');
run('cross-style-dataset-contract.contract.test.js');run('b3d-multiview-contract.contract.test.js');run('runtime-shadow-adapter.contract.test.js');run('generic-reproduction-policy.contract.test.js');
run('run_style_pipeline_v0_6c.js',['--workspace',path.join(B,'styles/y2k/style.workspace.json'),'--reuse-b1']);run('build_y2k_v0_6c_structural_outputs.js');run('build_cross_style_registry_v0_6c1.js');run('run_safe_foundation_integrity_audit_v0_6c.js');run('run_safe_foundation_integrity_audit_v0_6c1.js');
const after=Object.fromEntries(protectedFiles.map(f=>[f,hash(f)]));const changed=protectedFiles.filter(f=>before[f]!==after[f]);if(changed.length){console.error('❌ Protected scientific/calibration artifacts changed: '+changed.join(', '));process.exit(3)}
const report={metadata:{name:'YOYO Safe Foundation Sprint',version:'0.6C.1',status:'PASS',human_calibration_required:false,live_runtime_modified:false,legacy_calibration_modified:false},summary:{stages:stages.length,stages_passed:stages.filter(x=>x.status===0).length,protected_files_unchanged:true},protected_files:protectedFiles.map(f=>({file:f,sha256_before:before[f],sha256_after:after[f],unchanged:before[f]===after[f]})),stages};fs.writeFileSync(path.join(B,'safe_foundation_sprint_report_v0_6c1.json'),JSON.stringify(report,null,2)+'\n');run('build_project_state_manifest_v0_6c1.js');
console.log('\n✅ Safe Foundation Sprint v0.6C.1 PASS.');console.log('✅ Legacy calibration_set_v0_human.json preserved as immutable historical raw.');console.log('✅ Active v0.4 train + v0.5.2 holdout satisfy the new perceptual label schema.');console.log('✅ Legacy low-chroma inconsistencies are quarantined as review candidates, not auto-edited.');console.log('✅ Cross-style structural registry cannot propagate legacy calibration labels.');console.log('✅ Future cross-style perceptual labels must obey low_chroma → not_applicable.');console.log('✅ Human Tone/Hue calibration remains paused.');console.log('✅ Live runtime integration remains OFF.');
